//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bytePassion.OnkoTePla.Resources.Languages.ClientLang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Client {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Client() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bytePassion.OnkoTePla.Resources.Languages.ClientLang.Client", typeof(Client).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017 bytePassion.
        /// </summary>
        public static string AboutDialog_Copyright {
            get {
                return ResourceManager.GetString("AboutDialog_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string AboutDialog_DeveloperSectionHeader {
            get {
                return ResourceManager.GetString("AboutDialog_DeveloperSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is under Apache 2.0 Licence.
        /// </summary>
        public static string AboutDialog_LicenceText {
            get {
                return ResourceManager.GetString("AboutDialog_LicenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        public static string AddAppointmentDialog_BeginHeader {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_BeginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddAppointmentDialog_CancelButtonCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AddAppointmentDialog_CreateButtonCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_CreateButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string AddAppointmentDialog_DescriptionHeader {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string AddAppointmentDialog_DurationHeader {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_DurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier appointment begin.
        /// </summary>
        public static string AddAppointmentDialog_EarlierButtonCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_EarlierButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier begin not possible.
        /// </summary>
        public static string AddAppointmentDialog_EarlierButtonNotPossibleCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_EarlierButtonNotPossibleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: No appointment description entered.
        /// </summary>
        public static string AddAppointmentDialog_Hint_NoDescription {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_Hint_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: No patient selected.
        /// </summary>
        public static string AddAppointmentDialog_Hint_NoPatient {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_Hint_NoPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: There is no space for that appointment.
        /// </summary>
        public static string AddAppointmentDialog_Hint_NoSpace {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_Hint_NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: This patient has already an appointment that day.
        /// </summary>
        public static string AddAppointmentDialog_Hint_PatientHasAlreadyAppointment {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_Hint_PatientHasAlreadyAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description here.
        /// </summary>
        public static string AddAppointmentDialog_HintText_Description {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_HintText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string AddAppointmentDialog_HourLabelCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_HourLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string AddAppointmentDialog_LabelSectionHeader {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_LabelSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later appointment begin.
        /// </summary>
        public static string AddAppointmentDialog_LaterButtonCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_LaterButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later begin not possible.
        /// </summary>
        public static string AddAppointmentDialog_LaterButtonNotPossibleCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_LaterButtonNotPossibleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string AddAppointmentDialog_MinuteLabelCaption {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_MinuteLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - no patient selected -.
        /// </summary>
        public static string AddAppointmentDialog_NoPatientSelectedText {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_NoPatientSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string AddAppointmentDialog_PatientSectionHeader {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_PatientSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new appointment.
        /// </summary>
        public static string AddAppointmentDialog_Title {
            get {
                return ResourceManager.GetString("AddAppointmentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment count:.
        /// </summary>
        public static string AppointmentCount_Caption {
            get {
                return ResourceManager.GetString("AppointmentCount_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm changes.
        /// </summary>
        public static string AppointmentEditButton_ConfirmChanges_ToolTip {
            get {
                return ResourceManager.GetString("AppointmentEditButton_ConfirmChanges_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string AppointmentEditButton_Copy_ToolTip {
            get {
                return ResourceManager.GetString("AppointmentEditButton_Copy_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string AppointmentEditButton_Delete_ToolTip {
            get {
                return ResourceManager.GetString("AppointmentEditButton_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes.
        /// </summary>
        public static string AppointmentEditButton_DiscardChanges_ToolTip {
            get {
                return ResourceManager.GetString("AppointmentEditButton_DiscardChanges_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit description and label.
        /// </summary>
        public static string AppointmentEditButton_Edit_ToolTip {
            get {
                return ResourceManager.GetString("AppointmentEditButton_Edit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AppointmentLocationSelectionDialog_CancelButtonCaption {
            get {
                return ResourceManager.GetString("AppointmentLocationSelectionDialog_CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new appointment.
        /// </summary>
        public static string AppointmentLocationSelectionDialog_CreateAppointmentButtonCaption {
            get {
                return ResourceManager.GetString("AppointmentLocationSelectionDialog_CreateAppointmentButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AppointmentLocationSelectionDialog_DateSectionHeader {
            get {
                return ResourceManager.GetString("AppointmentLocationSelectionDialog_DateSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        public static string AppointmentLocationSelectionDialog_PracticeSectionHeader {
            get {
                return ResourceManager.GetString("AppointmentLocationSelectionDialog_PracticeSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected to server.
        /// </summary>
        public static string ConnectionStatus_Connected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected from server.
        /// </summary>
        public static string ConnectionStatus_Disconnected {
            get {
                return ResourceManager.GetString("ConnectionStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trying to connect .....
        /// </summary>
        public static string ConnectionStatus_TryingToConnect {
            get {
                return ResourceManager.GetString("ConnectionStatus_TryingToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trying to disconnect .....
        /// </summary>
        public static string ConnectionStatus_TryingToDisconnect {
            get {
                return ResourceManager.GetString("ConnectionStatus_TryingToDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DateSelector_TodayButtonCaption {
            get {
                return ResourceManager.GetString("DateSelector_TodayButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditAppointmentDialog_CancelButtonCaption {
            get {
                return ResourceManager.GetString("EditAppointmentDialog_CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EditAppointmentDialog_DescriptionSectionHeader {
            get {
                return ResourceManager.GetString("EditAppointmentDialog_DescriptionSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description here.
        /// </summary>
        public static string EditAppointmentDialog_HintText_Description {
            get {
                return ResourceManager.GetString("EditAppointmentDialog_HintText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string EditAppointmentDialog_LabelSectionHeader {
            get {
                return ResourceManager.GetString("EditAppointmentDialog_LabelSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string EditAppointmentDialog_OkButtonCaption {
            get {
                return ResourceManager.GetString("EditAppointmentDialog_OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit appointment.
        /// </summary>
        public static string EditAppointmentDialog_Title {
            get {
                return ResourceManager.GetString("EditAppointmentDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must not contain the following characters:.
        /// </summary>
        public static string ErrorMessage_CharacterError_Description_Msg {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_Description_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputerror.
        /// </summary>
        public static string ErrorMessage_CharacterError_Title {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cannot be established.
        /// </summary>
        public static string ErrorMessage_ConnectionInitError_AfterIp {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionInitError_AfterIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to.
        /// </summary>
        public static string ErrorMessage_ConnectionInitError_BeforeIp {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionInitError_BeforeIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to the server is lost..
        /// </summary>
        public static string ErrorMessage_ConnectionProblem_Msg_Part1 {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionProblem_Msg_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can try again in 15 seconds..
        /// </summary>
        public static string ErrorMessage_ConnectionProblem_Msg_Part2 {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionProblem_Msg_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection-Problem.
        /// </summary>
        public static string ErrorMessage_ConnectionProblem_Title {
            get {
                return ResourceManager.GetString("ErrorMessage_ConnectionProblem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a valid IP-address.
        /// </summary>
        public static string ErrorMessage_InvalidIp {
            get {
                return ResourceManager.GetString("ErrorMessage_InvalidIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login not possible.
        /// </summary>
        public static string ErrorMessage_LoginError {
            get {
                return ResourceManager.GetString("ErrorMessage_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already logged in.
        /// </summary>
        public static string ErrorMessage_LoginErrorReason_UserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("ErrorMessage_LoginErrorReason_UserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is incorrect.
        /// </summary>
        public static string ErrorMessage_LoginErrorReason_WrongPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_LoginErrorReason_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal and very unexpected error Occured.
        /// </summary>
        public static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from server .....
        /// </summary>
        public static string LoadingPage_Text {
            get {
                return ResourceManager.GetString("LoadingPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoconnect on next start.
        /// </summary>
        public static string LoginPage_AutoConnectCheckboxCaption {
            get {
                return ResourceManager.GetString("LoginPage_AutoConnectCheckboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string LoginPage_ConnectButtonCaption {
            get {
                return ResourceManager.GetString("LoginPage_ConnectButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection settings.
        /// </summary>
        public static string LoginPage_ConnectionSettingsSectionHeader {
            get {
                return ResourceManager.GetString("LoginPage_ConnectionSettingsSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string LoginPage_DisconnectButtonCaption {
            get {
                return ResourceManager.GetString("LoginPage_DisconnectButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPage_Header {
            get {
                return ResourceManager.GetString("LoginPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password here.
        /// </summary>
        public static string LoginPage_HintText_Password {
            get {
                return ResourceManager.GetString("LoginPage_HintText_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter server address here.
        /// </summary>
        public static string LoginPage_HintText_ServerAddress {
            get {
                return ResourceManager.GetString("LoginPage_HintText_ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string LoginPage_PasswordPromt {
            get {
                return ResourceManager.GetString("LoginPage_PasswordPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server-Ip-Address (e.g.: 192.128.1.234):.
        /// </summary>
        public static string LoginPage_ServerIpPromt {
            get {
                return ResourceManager.GetString("LoginPage_ServerIpPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        public static string LoginPage_UserPromt {
            get {
                return ResourceManager.GetString("LoginPage_UserPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du you want to close the application?.
        /// </summary>
        public static string MainWindow_CloseWindow_Text {
            get {
                return ResourceManager.GetString("MainWindow_CloseWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        public static string MainWindow_CloseWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_CloseWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editing could not be completed. Please try again!.
        /// </summary>
        public static string NotificationMsg_AddingEventsFailed {
            get {
                return ResourceManager.GetString("NotificationMsg_AddingEventsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding failed - please try again!.
        /// </summary>
        public static string NotificationMsg_AddingFailed {
            get {
                return ResourceManager.GetString("NotificationMsg_AddingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting failed - please try again!.
        /// </summary>
        public static string NotificationMsg_DeletingFailed {
            get {
                return ResourceManager.GetString("NotificationMsg_DeletingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editing was aborted because of conflicts.
        /// </summary>
        public static string NotificationMsg_EndedBecauseOfConflict {
            get {
                return ResourceManager.GetString("NotificationMsg_EndedBecauseOfConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The undo/redo-history will be reseted..
        /// </summary>
        public static string NotificationMsg_EventHistoryWillBeReseted {
            get {
                return ResourceManager.GetString("NotificationMsg_EventHistoryWillBeReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification failed - please try again!.
        /// </summary>
        public static string NotificationMsg_ModifyingFailed {
            get {
                return ResourceManager.GetString("NotificationMsg_ModifyingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page cannot be viewed, because an appointment is being edited.
        /// </summary>
        public static string NotificationMsg_PageCannotBeChanged {
            get {
                return ResourceManager.GetString("NotificationMsg_PageCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo not possible..
        /// </summary>
        public static string NotificationMsg_RedoNotPossible {
            get {
                return ResourceManager.GetString("NotificationMsg_RedoNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move an appointment to a day where the practice is not open!.
        /// </summary>
        public static string NotificationMsg_SendAppointmentToClosedDay {
            get {
                return ResourceManager.GetString("NotificationMsg_SendAppointmentToClosedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move the appointment to this day, because no free slot is big enough.
        /// </summary>
        public static string NotificationMsg_SendAppointmentToNoSpace {
            get {
                return ResourceManager.GetString("NotificationMsg_SendAppointmentToNoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment cannot be placed here - too many appointments are starting to close.
        /// </summary>
        public static string NotificationMsg_SlotProtectionViolation {
            get {
                return ResourceManager.GetString("NotificationMsg_SlotProtectionViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appointment cannot be placed here - the patient has already an appointment on this day.
        /// </summary>
        public static string NotificationMsg_TooManyPatientsAtDay {
            get {
                return ResourceManager.GetString("NotificationMsg_TooManyPatientsAtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo not possible..
        /// </summary>
        public static string NotificationMsg_UndoNotPossible {
            get {
                return ResourceManager.GetString("NotificationMsg_UndoNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show protected zones.
        /// </summary>
        public static string OptionsPage_ProtectionZoneViewMode_Always {
            get {
                return ResourceManager.GetString("OptionsPage_ProtectionZoneViewMode_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never show protected zones.
        /// </summary>
        public static string OptionsPage_ProtectionZoneViewMode_DoNotShow {
            get {
                return ResourceManager.GetString("OptionsPage_ProtectionZoneViewMode_DoNotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show protected zones only while editing.
        /// </summary>
        public static string OptionsPage_ProtectionZoneViewMode_OnlyInEdit {
            get {
                return ResourceManager.GetString("OptionsPage_ProtectionZoneViewMode_OnlyInEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your language:.
        /// </summary>
        public static string OptionsPage_SelectLanguagePromt {
            get {
                return ResourceManager.GetString("OptionsPage_SelectLanguagePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose SlotProtection visibility:.
        /// </summary>
        public static string OptionsPage_SelectProtectionZoneViewModePromt {
            get {
                return ResourceManager.GetString("OptionsPage_SelectProtectionZoneViewModePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string OverviewPage_ClosedPracticeText {
            get {
                return ResourceManager.GetString("OverviewPage_ClosedPracticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string OverviewPage_NavigationSectionHeader {
            get {
                return ResourceManager.GetString("OverviewPage_NavigationSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pactice.
        /// </summary>
        public static string OverviewPage_PracticeSectionHeader {
            get {
                return ResourceManager.GetString("OverviewPage_PracticeSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string OverviewPage_RoomSectionHeader {
            get {
                return ResourceManager.GetString("OverviewPage_RoomSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rooms.
        /// </summary>
        public static string RoomSelector_AllRoomsItem {
            get {
                return ResourceManager.GetString("RoomSelector_AllRoomsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the appointment?.
        /// </summary>
        public static string SearchPage_DeletingAppointmentPrompt {
            get {
                return ResourceManager.GetString("SearchPage_DeletingAppointmentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments existant.
        /// </summary>
        public static string SearchPage_NoAppointmentsText {
            get {
                return ResourceManager.GetString("SearchPage_NoAppointmentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - no patient selected -.
        /// </summary>
        public static string SearchPage_NoPatientSelected {
            get {
                return ResourceManager.GetString("SearchPage_NoPatientSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [not accessable practice].
        /// </summary>
        public static string SearchPage_NotAccessablePractice {
            get {
                return ResourceManager.GetString("SearchPage_NotAccessablePractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show earlier appointments.
        /// </summary>
        public static string SearchPage_ShowEarlierAppointmentsCheckBoxCaption {
            get {
                return ResourceManager.GetString("SearchPage_ShowEarlierAppointmentsCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the previous created appointment?.
        /// </summary>
        public static string StringGenerator_DeletingAppointment {
            get {
                return ResourceManager.GetString("StringGenerator_DeletingAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After redo-action.
        /// </summary>
        public static string StringGenerator_Part_AfterRedoAction {
            get {
                return ResourceManager.GetString("StringGenerator_Part_AfterRedoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After undo-action.
        /// </summary>
        public static string StringGenerator_Part_AfterUndoAction {
            get {
                return ResourceManager.GetString("StringGenerator_Part_AfterUndoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string StringGenerator_Part_Current {
            get {
                return ResourceManager.GetString("StringGenerator_Part_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string StringGenerator_Part_Description {
            get {
                return ResourceManager.GetString("StringGenerator_Part_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string StringGenerator_Part_From {
            get {
                return ResourceManager.GetString("StringGenerator_Part_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string StringGenerator_Part_Label {
            get {
                return ResourceManager.GetString("StringGenerator_Part_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to therapy-place.
        /// </summary>
        public static string StringGenerator_Part_TherapyPlace {
            get {
                return ResourceManager.GetString("StringGenerator_Part_TherapyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string StringGenerator_Part_To {
            get {
                return ResourceManager.GetString("StringGenerator_Part_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restore the previous deleted appointment?.
        /// </summary>
        public static string StringGenerator_ReaddAppointment {
            get {
                return ResourceManager.GetString("StringGenerator_ReaddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restore the movement of the appointment of.
        /// </summary>
        public static string StringGenerator_RedoDividedMoveAppointment_Part1 {
            get {
                return ResourceManager.GetString("StringGenerator_RedoDividedMoveAppointment_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string StringGenerator_RedoDividedMoveAppointment_Part2 {
            get {
                return ResourceManager.GetString("StringGenerator_RedoDividedMoveAppointment_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du you want to restore the modification of the appointment of.
        /// </summary>
        public static string StringGenerator_RedoReplaceAppointment_Part1 {
            get {
                return ResourceManager.GetString("StringGenerator_RedoReplaceAppointment_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string StringGenerator_RedoReplaceAppointment_Part2 {
            get {
                return ResourceManager.GetString("StringGenerator_RedoReplaceAppointment_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move the appointment of.
        /// </summary>
        public static string StringGenerator_UndoDividedMoveAppointment_Part1 {
            get {
                return ResourceManager.GetString("StringGenerator_UndoDividedMoveAppointment_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back?.
        /// </summary>
        public static string StringGenerator_UndoDividedMoveAppointment_Part2 {
            get {
                return ResourceManager.GetString("StringGenerator_UndoDividedMoveAppointment_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du you want to take back the modification of the appointment of.
        /// </summary>
        public static string StringGenerator_UndoReplaceAppointment_Part1 {
            get {
                return ResourceManager.GetString("StringGenerator_UndoReplaceAppointment_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string StringGenerator_UndoReplaceAppointment_Part2 {
            get {
                return ResourceManager.GetString("StringGenerator_UndoReplaceAppointment_Part2", resourceCulture);
            }
        }
    }
}
