//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OQF.Visualization.Resources.LanguageDictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Captions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Captions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OQF.Visualization.Resources.LanguageDictionaries.Captions", typeof(Captions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string AP_ApplicationSectionHeader {
            get {
                return ResourceManager.GetString("AP_ApplicationSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers.
        /// </summary>
        public static string AP_DeveloperSectionHeader {
            get {
                return ResourceManager.GetString("AP_DeveloperSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string AP_LicenceSectionHeader {
            get {
                return ResourceManager.GetString("AP_LicenceSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About OpenQuoridorFramework.
        /// </summary>
        public static string AP_PageHeader {
            get {
                return ResourceManager.GetString("AP_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventor.
        /// </summary>
        public static string AP_QuoridorInventorSubItem {
            get {
                return ResourceManager.GetString("AP_QuoridorInventorSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string AP_QuoridorPublisherSubItem {
            get {
                return ResourceManager.GetString("AP_QuoridorPublisherSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoridor.
        /// </summary>
        public static string AP_QuoridorSectionHeader {
            get {
                return ResourceManager.GetString("AP_QuoridorSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceCode.
        /// </summary>
        public static string AP_SourceCodeSectionHeader {
            get {
                return ResourceManager.GetString("AP_SourceCodeSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sourceCode of the OpenQuoridorFramework can be found on gitHub (https://github.com/bytePassion/OpenQuoridorFramework.git)..
        /// </summary>
        public static string AP_SourceCodeSectionText {
            get {
                return ResourceManager.GetString("AP_SourceCodeSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Party Usages.
        /// </summary>
        public static string AP_ThirdPartySectionHeader {
            get {
                return ResourceManager.GetString("AP_ThirdPartySectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string AP_VersionSectionHeader {
            get {
                return ResourceManager.GetString("AP_VersionSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want exit during a ongoing game?.
        /// </summary>
        public static string ClosingDialogMessage {
            get {
                return ResourceManager.GetString("ClosingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is empty or invalid.
        /// </summary>
        public static string FVR_EmptyOrInvalidFile {
            get {
                return ResourceManager.GetString("FVR_EmptyOrInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains an invalid move.
        /// </summary>
        public static string FVR_FileContainsInvalidMove {
            get {
                return ResourceManager.GetString("FVR_FileContainsInvalidMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file contains a game which already ended.
        /// </summary>
        public static string FVR_FileContainsTerminatedGame {
            get {
                return ResourceManager.GetString("FVR_FileContainsTerminatedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardState.
        /// </summary>
        public static string HTWAB_BoardStateParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_BoardStateParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_BoardStateParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_BoardStateParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examplary implementation.
        /// </summary>
        public static string HTWAB_ExampleParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_ExampleParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_ExampleParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_ExampleParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldCoordinate.
        /// </summary>
        public static string HTWAB_FieldCoordinateParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_FieldCoordinateParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_FieldCoordinateParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_FieldCoordinateParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameContraints.
        /// </summary>
        public static string HTWAB_GameConstraintsParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_GameConstraintsParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GameConstraintsParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_GameConstraintsParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GameFlowItem1 {
            get {
                return ResourceManager.GetString("HTWAB_GameFlowItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GameFlowItem2 {
            get {
                return ResourceManager.GetString("HTWAB_GameFlowItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GameFlowItem3 {
            get {
                return ResourceManager.GetString("HTWAB_GameFlowItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GameFlowItem4 {
            get {
                return ResourceManager.GetString("HTWAB_GameFlowItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GameFlowItem5 {
            get {
                return ResourceManager.GetString("HTWAB_GameFlowItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameflow from the point of a bot.
        /// </summary>
        public static string HTWAB_GameFlowParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_GameFlowParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GeneralProceedingItem1 {
            get {
                return ResourceManager.GetString("HTWAB_GeneralProceedingItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GeneralProceedingItem2 {
            get {
                return ResourceManager.GetString("HTWAB_GeneralProceedingItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GeneralProceedingItem3 {
            get {
                return ResourceManager.GetString("HTWAB_GeneralProceedingItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GeneralProceedingItem4 {
            get {
                return ResourceManager.GetString("HTWAB_GeneralProceedingItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_GeneralProceedingItem5 {
            get {
                return ResourceManager.GetString("HTWAB_GeneralProceedingItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Proceeding.
        /// </summary>
        public static string HTWAB_GeneralProceedingParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_GeneralProceedingParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string HTWAB_HintParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_HintParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_HintParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_HintParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Classes/Enums/Structs at the OQF.Bot.Contracts.dll.
        /// </summary>
        public static string HTWAB_ImportantClassesParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_ImportantClassesParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_ImportantClassesParagraphNote {
            get {
                return ResourceManager.GetString("HTWAB_ImportantClassesParagraphNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move(s).
        /// </summary>
        public static string HTWAB_MovesParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_MovesParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_MovesParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_MovesParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to write a bot.
        /// </summary>
        public static string HTWAB_PageHeader {
            get {
                return ResourceManager.GetString("HTWAB_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player and PlayerState.
        /// </summary>
        public static string HTWAB_PlayerAndStateParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_PlayerAndStateParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_PlayerAndStateParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_PlayerAndStateParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        public static string HTWAB_WallParagraphHeader {
            get {
                return ResourceManager.GetString("HTWAB_WallParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string HTWAB_WallParagraphText {
            get {
                return ResourceManager.GetString("HTWAB_WallParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string IP_AboutButtonCaption {
            get {
                return ResourceManager.GetString("IP_AboutButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Help.
        /// </summary>
        public static string IP_BotVsBotIntoButtonCaption {
            get {
                return ResourceManager.GetString("IP_BotVsBotIntoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string IP_CloseButtonCaption {
            get {
                return ResourceManager.GetString("IP_CloseButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to write a bot.
        /// </summary>
        public static string IP_HowToWriteABotButtonCaption {
            get {
                return ResourceManager.GetString("IP_HowToWriteABotButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Help.
        /// </summary>
        public static string IP_PlayerVsBotInfoButtonCaption {
            get {
                return ResourceManager.GetString("IP_PlayerVsBotInfoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoridor Notation.
        /// </summary>
        public static string IP_QuoridorNotationButtonCaption {
            get {
                return ResourceManager.GetString("IP_QuoridorNotationButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoridor Rules.
        /// </summary>
        public static string IP_QuoridorRulesButtonCaption {
            get {
                return ResourceManager.GetString("IP_QuoridorRulesButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Help.
        /// </summary>
        public static string IP_ReplayViewerInfoButtonCaption {
            get {
                return ResourceManager.GetString("IP_ReplayViewerInfoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Help.
        /// </summary>
        public static string IP_TurnamentInfoButtonCaption {
            get {
                return ResourceManager.GetString("IP_TurnamentInfoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ND_OkButtonCaption {
            get {
                return ResourceManager.GetString("ND_OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scroll down.
        /// </summary>
        public static string PvB_AutoScrollDownCheckBoxCaption {
            get {
                return ResourceManager.GetString("PvB_AutoScrollDownCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Name.
        /// </summary>
        public static string PvB_BotNameLabelCaption {
            get {
                return ResourceManager.GetString("PvB_BotNameLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Bot-DLL.
        /// </summary>
        public static string PvB_BrowseForBotButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_BrowseForBotButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitulate.
        /// </summary>
        public static string PvB_CapitulateButtonCaption {
            get {
                return ResourceManager.GetString("PvB_CapitulateButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string PvB_DebugCaption {
            get {
                return ResourceManager.GetString("PvB_DebugCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current Debug output.
        /// </summary>
        public static string PvB_DumpDebugFileDialogTitle {
            get {
                return ResourceManager.GetString("PvB_DumpDebugFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PvB_DumpDebugToFileButtonCaption {
            get {
                return ResourceManager.GetString("PvB_DumpDebugToFileButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current Progress.
        /// </summary>
        public static string PvB_DumpProgressFileDialogTitle {
            get {
                return ResourceManager.GetString("PvB_DumpProgressFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PvB_DumpProgressToFileButtonCaption {
            get {
                return ResourceManager.GetString("PvB_DumpProgressToFileButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot cannot be loaded as assembly.
        /// </summary>
        public static string PvB_ErrorMsg_BotCanNotBeLoadedFromAsembly {
            get {
                return ResourceManager.GetString("PvB_ErrorMsg_BotCanNotBeLoadedFromAsembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string PvB_ErrorMsg_FileDoesNotExist {
            get {
                return ResourceManager.GetString("PvB_ErrorMsg_FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is no valid assembly.
        /// </summary>
        public static string PvB_ErrorMsg_FileIsNoAssembly {
            get {
                return ResourceManager.GetString("PvB_ErrorMsg_FileIsNoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to choose a Bot-DLL before Starting a game.
        /// </summary>
        public static string PvB_ErrorMsg_NoDllPath {
            get {
                return ResourceManager.GetString("PvB_ErrorMsg_NoDllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text-file connot be loaded as progress-file.
        /// </summary>
        public static string PvB_ErrorMsg_ProgressFileCannotBeLoaded {
            get {
                return ResourceManager.GetString("PvB_ErrorMsg_ProgressFileCannotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string PvB_ErrorMsg_Reason {
            get {
                return ResourceManager.GetString("PvB_ErrorMsg_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PvB_HeaderCaptionPlayer {
            get {
                return ResourceManager.GetString("PvB_HeaderCaptionPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking-Time left.
        /// </summary>
        public static string PvB_MaximalThinkingTimeLabelCaption {
            get {
                return ResourceManager.GetString("PvB_MaximalThinkingTimeLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves left.
        /// </summary>
        public static string PvB_MovesLeftLabelCaption {
            get {
                return ResourceManager.GetString("PvB_MovesLeftLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and About.
        /// </summary>
        public static string PvB_OpenInfoButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_OpenInfoButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Progress.
        /// </summary>
        public static string PvB_ProgressCaption {
            get {
                return ResourceManager.GetString("PvB_ProgressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game Progress of currently ended game.
        /// </summary>
        public static string PvB_SaveGameProgressFileDialogTitle {
            get {
                return ResourceManager.GetString("PvB_SaveGameProgressFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string PvB_StartGameButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_StartGameButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game from Progress-File.
        /// </summary>
        public static string PvB_StartWithProgressGameButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_StartWithProgressGameButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls.
        /// </summary>
        public static string PvB_WallsLeftLabelCaption {
            get {
                return ResourceManager.GetString("PvB_WallsLeftLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation01 {
            get {
                return ResourceManager.GetString("PvBH_Explanation01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation02 {
            get {
                return ResourceManager.GetString("PvBH_Explanation02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation03 {
            get {
                return ResourceManager.GetString("PvBH_Explanation03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation04 {
            get {
                return ResourceManager.GetString("PvBH_Explanation04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation05 {
            get {
                return ResourceManager.GetString("PvBH_Explanation05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation06 {
            get {
                return ResourceManager.GetString("PvBH_Explanation06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation07 {
            get {
                return ResourceManager.GetString("PvBH_Explanation07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation08 {
            get {
                return ResourceManager.GetString("PvBH_Explanation08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation09 {
            get {
                return ResourceManager.GetString("PvBH_Explanation09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation10 {
            get {
                return ResourceManager.GetString("PvBH_Explanation10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation11 {
            get {
                return ResourceManager.GetString("PvBH_Explanation11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation12 {
            get {
                return ResourceManager.GetString("PvBH_Explanation12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation13 {
            get {
                return ResourceManager.GetString("PvBH_Explanation13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation14 {
            get {
                return ResourceManager.GetString("PvBH_Explanation14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation15 {
            get {
                return ResourceManager.GetString("PvBH_Explanation15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation16 {
            get {
                return ResourceManager.GetString("PvBH_Explanation16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation17 {
            get {
                return ResourceManager.GetString("PvBH_Explanation17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation18 {
            get {
                return ResourceManager.GetString("PvBH_Explanation18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation19 {
            get {
                return ResourceManager.GetString("PvBH_Explanation19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation20 {
            get {
                return ResourceManager.GetString("PvBH_Explanation20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Explanation21 {
            get {
                return ResourceManager.GetString("PvBH_Explanation21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string PvBH_Note {
            get {
                return ResourceManager.GetString("PvBH_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview to &apos;Player vs Bot&apos;.
        /// </summary>
        public static string PvBH_PageHeader {
            get {
                return ResourceManager.GetString("PvBH_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string QNP_ExampleParagraphHeader {
            get {
                return ResourceManager.GetString("QNP_ExampleParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QNP_ExampleParagraphText {
            get {
                return ResourceManager.GetString("QNP_ExampleParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move (Figure).
        /// </summary>
        public static string QNP_FigureMoveParagraphHeader {
            get {
                return ResourceManager.GetString("QNP_FigureMoveParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QNP_FigureMoveParagraphText {
            get {
                return ResourceManager.GetString("QNP_FigureMoveParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string QNP_GeneralParagraphHeader {
            get {
                return ResourceManager.GetString("QNP_GeneralParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QNP_GeneralParagraphText {
            get {
                return ResourceManager.GetString("QNP_GeneralParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoridor - Notation.
        /// </summary>
        public static string QNP_PageHeader {
            get {
                return ResourceManager.GetString("QNP_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 1.
        /// </summary>
        public static string QNP_Picture1Caption {
            get {
                return ResourceManager.GetString("QNP_Picture1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 2.
        /// </summary>
        public static string QNP_Picture2Caption {
            get {
                return ResourceManager.GetString("QNP_Picture2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Board.
        /// </summary>
        public static string QNP_TheBoardParagraphHeader {
            get {
                return ResourceManager.GetString("QNP_TheBoardParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QNP_TheBoardParagraphText {
            get {
                return ResourceManager.GetString("QNP_TheBoardParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move (Wall).
        /// </summary>
        public static string QNP_WallMoveParagraphHeader {
            get {
                return ResourceManager.GetString("QNP_WallMoveParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QNP_WallMoveParagraphText {
            get {
                return ResourceManager.GetString("QNP_WallMoveParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Flow.
        /// </summary>
        public static string QRP_GameFlowParagraphHeader {
            get {
                return ResourceManager.GetString("QRP_GameFlowParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QRP_GameFlowParagraphText {
            get {
                return ResourceManager.GetString("QRP_GameFlowParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Goal.
        /// </summary>
        public static string QRP_GameGoalParagraphHeader {
            get {
                return ResourceManager.GetString("QRP_GameGoalParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QRP_GameGoalParagraphText {
            get {
                return ResourceManager.GetString("QRP_GameGoalParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Setup.
        /// </summary>
        public static string QRP_GameSetupParagraphHeader {
            get {
                return ResourceManager.GetString("QRP_GameSetupParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QRP_GameSetupParagraphText {
            get {
                return ResourceManager.GetString("QRP_GameSetupParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string QRP_GeneralParagraphHeader {
            get {
                return ResourceManager.GetString("QRP_GeneralParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QRP_GeneralParagraphText {
            get {
                return ResourceManager.GetString("QRP_GeneralParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quoridor - Rules.
        /// </summary>
        public static string QRP_PageHeader {
            get {
                return ResourceManager.GetString("QRP_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 1.
        /// </summary>
        public static string QRP_Picture1Caption {
            get {
                return ResourceManager.GetString("QRP_Picture1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 2.
        /// </summary>
        public static string QRP_Picture2Caption {
            get {
                return ResourceManager.GetString("QRP_Picture2Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 3.
        /// </summary>
        public static string QRP_Picture3Caption {
            get {
                return ResourceManager.GetString("QRP_Picture3Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 4.
        /// </summary>
        public static string QRP_Picture4Caption {
            get {
                return ResourceManager.GetString("QRP_Picture4Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture 5.
        /// </summary>
        public static string QRP_Picture5Caption {
            get {
                return ResourceManager.GetString("QRP_Picture5Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special moving rules.
        /// </summary>
        public static string QRP_SpecialMoveParagraphHeader {
            get {
                return ResourceManager.GetString("QRP_SpecialMoveParagraphHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO.
        /// </summary>
        public static string QRP_SpecialMoveParagraphText {
            get {
                return ResourceManager.GetString("QRP_SpecialMoveParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current game progress?.
        /// </summary>
        public static string SavingDialogMessage {
            get {
                return ResourceManager.GetString("SavingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sry ... you got beaten by the bot.
        /// </summary>
        public static string WD_LoosingMessage {
            get {
                return ResourceManager.GetString("WD_LoosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string WD_Message_Reason {
            get {
                return ResourceManager.GetString("WD_Message_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string WD_NoButtonCaption {
            get {
                return ResourceManager.GetString("WD_NoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the Game?.
        /// </summary>
        public static string WD_SaveGameRequest {
            get {
                return ResourceManager.GetString("WD_SaveGameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You beated the bot!.
        /// </summary>
        public static string WD_WinningMessage {
            get {
                return ResourceManager.GetString("WD_WinningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string WD_YesButtonCaption {
            get {
                return ResourceManager.GetString("WD_YesButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitulation.
        /// </summary>
        public static string WinningReason_Capitulation {
            get {
                return ResourceManager.GetString("WinningReason_Capitulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum of allowed moves was exceeded.
        /// </summary>
        public static string WinningReason_ExceedanceOfMaxMoves {
            get {
                return ResourceManager.GetString("WinningReason_ExceedanceOfMaxMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum thought time was exceeded.
        /// </summary>
        public static string WinningReason_ExceedanceOfThoughtTime {
            get {
                return ResourceManager.GetString("WinningReason_ExceedanceOfThoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid move.
        /// </summary>
        public static string WinningReason_InvalidMode {
            get {
                return ResourceManager.GetString("WinningReason_InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular win (first on the other side).
        /// </summary>
        public static string WinningReason_RegularQuoridorWin {
            get {
                return ResourceManager.GetString("WinningReason_RegularQuoridorWin", resourceCulture);
            }
        }
    }
}
