//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OQF.Visualization.Resources.LanguageDictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Captions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Captions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OQF.Visualization.Resources.LanguageDictionaries.Captions", typeof(Captions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto scroll down.
        /// </summary>
        public static string PvB_AutoScrollDownCheckBoxCaption {
            get {
                return ResourceManager.GetString("PvB_AutoScrollDownCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Name.
        /// </summary>
        public static string PvB_BotNameLabelCaption {
            get {
                return ResourceManager.GetString("PvB_BotNameLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for Bot-DLL.
        /// </summary>
        public static string PvB_BrowseForBotButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_BrowseForBotButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitulate.
        /// </summary>
        public static string PvB_CapitulateButtonCaption {
            get {
                return ResourceManager.GetString("PvB_CapitulateButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string PvB_DebugCaption {
            get {
                return ResourceManager.GetString("PvB_DebugCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PvB_HeaderCaptionPlayer {
            get {
                return ResourceManager.GetString("PvB_HeaderCaptionPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking-Time left.
        /// </summary>
        public static string PvB_MaximalThinkingTimeLabelCaption {
            get {
                return ResourceManager.GetString("PvB_MaximalThinkingTimeLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and About.
        /// </summary>
        public static string PvB_OpenInfoButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_OpenInfoButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Progress.
        /// </summary>
        public static string PvB_ProgressCaption {
            get {
                return ResourceManager.GetString("PvB_ProgressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string PvB_StartGameButtonToolTipCaption {
            get {
                return ResourceManager.GetString("PvB_StartGameButtonToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walls.
        /// </summary>
        public static string PvB_WallsLeftLabelCaption {
            get {
                return ResourceManager.GetString("PvB_WallsLeftLabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sry ... you got beaten by the bot.
        /// </summary>
        public static string WD_LoosingMessage {
            get {
                return ResourceManager.GetString("WD_LoosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string WD_Message_Reason {
            get {
                return ResourceManager.GetString("WD_Message_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string WD_NoButtonCaption {
            get {
                return ResourceManager.GetString("WD_NoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the Game?.
        /// </summary>
        public static string WD_SaveGameRequest {
            get {
                return ResourceManager.GetString("WD_SaveGameRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You beated the bot!.
        /// </summary>
        public static string WD_WinningMessage {
            get {
                return ResourceManager.GetString("WD_WinningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string WD_YesButtonCaption {
            get {
                return ResourceManager.GetString("WD_YesButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bot exceeded its thought-time.
        /// </summary>
        public static string WinningReason_BotExceededThoughtTime {
            get {
                return ResourceManager.GetString("WinningReason_BotExceededThoughtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capitulation.
        /// </summary>
        public static string WinningReason_Capitulation {
            get {
                return ResourceManager.GetString("WinningReason_Capitulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum of allowed moved where exceeded.
        /// </summary>
        public static string WinningReason_ExceedanceOfMaxMoves {
            get {
                return ResourceManager.GetString("WinningReason_ExceedanceOfMaxMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid move.
        /// </summary>
        public static string WinningReason_InvalidMode {
            get {
                return ResourceManager.GetString("WinningReason_InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular win (first on the other side).
        /// </summary>
        public static string WinningReason_RegularQuoridorWin {
            get {
                return ResourceManager.GetString("WinningReason_RegularQuoridorWin", resourceCulture);
            }
        }
    }
}
