//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bytePassion.OnkoTePla.Resources.Languages.CommonLang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bytePassion.OnkoTePla.Resources.Languages.CommonLang.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add patient.
        /// </summary>
        public static string AddPatientDialog_AddPatientButtonCaption {
            get {
                return ResourceManager.GetString("AddPatientDialog_AddPatientButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string AddPatientDialog_BirthdayPromt {
            get {
                return ResourceManager.GetString("AddPatientDialog_BirthdayPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddPatientDialog_CancelButtonCaption {
            get {
                return ResourceManager.GetString("AddPatientDialog_CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: dd.mm.yyyy.
        /// </summary>
        public static string AddPatientDialog_FormatInfo {
            get {
                return ResourceManager.GetString("AddPatientDialog_FormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string AddPatientDialog_IdPromt {
            get {
                return ResourceManager.GetString("AddPatientDialog_IdPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string AddPatientDialog_NamePromt {
            get {
                return ResourceManager.GetString("AddPatientDialog_NamePromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Patient.
        /// </summary>
        public static string AddPatientDialog_Title {
            get {
                return ResourceManager.GetString("AddPatientDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not contain the following characters:.
        /// </summary>
        public static string ErrorMessage_CharacterError_Name_Msg {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_Name_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient-ID must not contain the following characters:.
        /// </summary>
        public static string ErrorMessage_CharacterError_PatientId_Msg {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_PatientId_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputerror.
        /// </summary>
        public static string ErrorMessage_CharacterError_Title {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_Title", resourceCulture);
            }
        }
    }
}
