//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bytePassion.OnkoTePla.Resources.Languages.CommonLang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bytePassion.OnkoTePla.Resources.Languages.CommonLang.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add patient.
        /// </summary>
        public static string AddPatientDialog_AddPatientButtonCaption {
            get {
                return ResourceManager.GetString("AddPatientDialog_AddPatientButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AddPatientDialog_CancelButtonCaption {
            get {
                return ResourceManager.GetString("AddPatientDialog_CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format: dd.mm.yyyy.
        /// </summary>
        public static string AddPatientDialog_FormatInfo {
            get {
                return ResourceManager.GetString("AddPatientDialog_FormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Patient.
        /// </summary>
        public static string AddPatientDialog_Title {
            get {
                return ResourceManager.GetString("AddPatientDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not contain the following characters:.
        /// </summary>
        public static string ErrorMessage_CharacterError_Name_Msg {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_Name_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient-ID must not contain the following characters:.
        /// </summary>
        public static string ErrorMessage_CharacterError_PatientId_Msg {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_PatientId_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputerror.
        /// </summary>
        public static string ErrorMessage_CharacterError_Title {
            get {
                return ResourceManager.GetString("ErrorMessage_CharacterError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string NotificationDialog_OkButtonCaption {
            get {
                return ResourceManager.GetString("NotificationDialog_OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new setting will be applied after restart of the application!.
        /// </summary>
        public static string NotificationMsg_LanguageSelector {
            get {
                return ResourceManager.GetString("NotificationMsg_LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new patient.
        /// </summary>
        public static string PatientSelector_AddPatientButtonNormal {
            get {
                return ResourceManager.GetString("PatientSelector_AddPatientButtonNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the patient.
        /// </summary>
        public static string PatientSelector_AddPatientButtonSpecial_Part1 {
            get {
                return ResourceManager.GetString("PatientSelector_AddPatientButtonSpecial_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string PatientSelector_AddPatientButtonSpecial_Part2 {
            get {
                return ResourceManager.GetString("PatientSelector_AddPatientButtonSpecial_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter patient name or ID.
        /// </summary>
        public static string PatientSelector_HintText_FilterTextBox {
            get {
                return ResourceManager.GetString("PatientSelector_HintText_FilterTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient birthday (dd.mm.yyy).
        /// </summary>
        public static string PatientSelector_HintText_NewPatientBirthday {
            get {
                return ResourceManager.GetString("PatientSelector_HintText_NewPatientBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient-ID.
        /// </summary>
        public static string PatientSelector_HintText_NewPatientId {
            get {
                return ResourceManager.GetString("PatientSelector_HintText_NewPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient name.
        /// </summary>
        public static string PatientSelector_HintText_NewPatientName {
            get {
                return ResourceManager.GetString("PatientSelector_HintText_NewPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patient available.
        /// </summary>
        public static string PatientSelector_NoPatientAvailable {
            get {
                return ResourceManager.GetString("PatientSelector_NoPatientAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No patient with this name or ID available.
        /// </summary>
        public static string PatientSelector_NoPatientWithThisNameOrIdAvailable {
            get {
                return ResourceManager.GetString("PatientSelector_NoPatientWithThisNameOrIdAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show deceased patients.
        /// </summary>
        public static string PatientSelector_ShowDeadPatientCheckBoxCaption {
            get {
                return ResourceManager.GetString("PatientSelector_ShowDeadPatientCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string YesNoDialog_NoButtonCaption {
            get {
                return ResourceManager.GetString("YesNoDialog_NoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesNoDialog_YesButtonCaption {
            get {
                return ResourceManager.GetString("YesNoDialog_YesButtonCaption", resourceCulture);
            }
        }
    }
}
